name: foodfox
description: FoodFox — FOX Food Xplorer (Android)
publish_to: "none"
version: 0.2.0+2

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  file_picker: ^8.1.4
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fox_logo.png
