#!/usr/bin/env bash
# Bump FoodFox version. Usage: bump-version.sh [build|patch|minor|major]
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:-build}"

semver="$(tr -d '[:space:]' < "$ROOT/VERSION")"
build="$(grep '^version:' "$ROOT/apps/mobile/pubspec.yaml" | sed -E 's/.*\+([0-9]+).*/\1/')"

IFS='.' read -r major minor patch <<< "$semver"

case "$MODE" in
  build)
    build=$((build + 1))
    ;;
  patch)
    patch=$((patch + 1))
    build=$((build + 1))
    semver="${major}.${minor}.${patch}"
    ;;
  minor)
    minor=$((minor + 1))
    patch=0
    build=$((build + 1))
    semver="${major}.${minor}.${patch}"
    ;;
  major)
    major=$((major + 1))
    minor=0
    patch=0
    build=$((build + 1))
    semver="${major}.${minor}.${patch}"
    ;;
  *)
    echo "Unknown mode: $MODE (use build|patch|minor|major)" >&2
    exit 1
    ;;
esac

printf '%s\n' "$semver" > "$ROOT/VERSION"

python3 - <<PY
from pathlib import Path
import re

root = Path("$ROOT")
semver = "$semver"
build = $build
full = f"{semver}+{build}"

pubspec = root / "apps/mobile/pubspec.yaml"
text = pubspec.read_text()
text = re.sub(r"^version: .*", f"version: {full}", text, count=1, flags=re.M)
pubspec.write_text(text)

pkg = root / "apps/web/package.json"
pkg_text = pkg.read_text()
pkg_text = re.sub(r'"version": "[^"]+"', f'"version": "{semver}"', pkg_text, count=1)
pkg.write_text(pkg_text)

dart = root / "apps/mobile/lib/version.dart"
dart.write_text(
    "// Generated by scripts/bump-version.sh — do not edit.\n"
    f"const String kAppVersion = '{semver}';\n"
    f"const int kAppBuild = {build};\n"
    f"const String kAppVersionLabel = '{semver} ({build})';\n"
)

ts = root / "apps/web/src/lib/version.ts"
ts.write_text(
    "// Generated by scripts/bump-version.sh — do not edit.\n"
    f'export const APP_VERSION = "{semver}";\n'
    f"export const APP_BUILD = {build};\n"
    f'export const APP_VERSION_LABEL = "{semver} ({build})";\n'
)

print(f"Bumped to {full}")
PY
