import "dart:convert";

import "package:flutter/services.dart" show rootBundle;

import "package:foodfox/models/models.dart";

/// Canned responses that stand in for the server in review builds.
///
/// The bundled payload is generated from the real FOX catalogue and scored by
/// the same recipe matcher the server uses, so every screen sees data in the
/// exact shape the API returns — the models below are parsed by the same
/// `fromJson` constructors used against the live backend.
///
/// Generated by `apps/mobile/tool/generate_demo_data.ts`.
class DemoBackend {
  DemoBackend._(this._data);

  static DemoBackend? _instance;

  final Map<String, dynamic> _data;
  List<ChatMessage>? _chat;
  int _replies = 0;

  static Future<DemoBackend> load() async {
    final cached = _instance;
    if (cached != null) return cached;
    final raw = await rootBundle.loadString("assets/demo/demo.json");
    final loaded = DemoBackend._(jsonDecode(raw) as Map<String, dynamic>);
    _instance = loaded;
    return loaded;
  }

  Map<String, dynamic> _section(String key) =>
      _data[key] as Map<String, dynamic>;

  ({UserProfile user, ClientProfile profile}) me() {
    final me = _section("me");
    return (
      user: UserProfile.fromJson(me["user"] as Map<String, dynamic>),
      profile: ClientProfile.fromJson(me["profile"] as Map<String, dynamic>),
    );
  }

  ({List<ResultItem> results, ZoneCounts counts}) results() {
    final section = _section("results");
    return (
      results: (section["results"] as List<dynamic>)
          .map((e) => ResultItem.fromJson(e as Map<String, dynamic>))
          .toList(),
      counts: ZoneCounts.fromJson(section["counts"] as Map<String, dynamic>),
    );
  }

  ({List<RecipeItem> recipes, int weekNumber, int suitableCount}) recipes() {
    final section = _section("recipes");
    return (
      recipes: (section["recipes"] as List<dynamic>)
          .map((e) => RecipeItem.fromJson(e as Map<String, dynamic>))
          .toList(),
      weekNumber: section["weekNumber"] as int? ?? 1,
      suitableCount: section["suitableCount"] as int? ?? 0,
    );
  }

  ({PlanData? plan, List<PlanWeekItem> weekTabs, int currentWeek}) plan({
    int? week,
  }) {
    final section = _section("plan");
    final shifted = _reanchorPlan(section["plan"] as Map<String, dynamic>);
    final plan = PlanData.fromJson(shifted);
    final tabs = plan.weeks
        .map(
          (w) => PlanWeekItem(
            weekNumber: w.weekNumber,
            phase: w.phase,
            days: const [],
          ),
        )
        .toList();

    final currentWeek = plan.weeks
        .firstWhere(
          (w) => w.days.any((d) => d.isToday),
          orElse: () => plan.weeks.first,
        )
        .weekNumber;

    // The server ships one week at a time and the screen loads the rest on
    // demand, so the demo has to answer the same way or the selected week
    // arrives empty.
    final wanted = week ?? currentWeek;
    return (
      plan: PlanData(
        planId: plan.planId,
        startedAt: plan.startedAt,
        weeks: plan.weeks.where((w) => w.weekNumber == wanted).toList(),
      ),
      weekTabs: tabs,
      currentWeek: currentWeek,
    );
  }

  /// The payload is generated once, so its dates would drift out from under
  /// the user. Slide the whole plan so it still started ten days ago and one
  /// of its days is genuinely today.
  Map<String, dynamic> _reanchorPlan(Map<String, dynamic> raw) {
    final generatedStart = DateTime.parse(raw["startedAt"] as String);
    final target = DateTime.now().subtract(const Duration(days: 10));
    final shift = DateTime(target.year, target.month, target.day).difference(
      DateTime(generatedStart.year, generatedStart.month, generatedStart.day),
    );
    final today = _dayKey(DateTime.now());

    final weeks = (raw["weeks"] as List<dynamic>).map((w) {
      final week = Map<String, dynamic>.from(w as Map<String, dynamic>);
      week["days"] = (week["days"] as List<dynamic>).map((d) {
        final day = Map<String, dynamic>.from(d as Map<String, dynamic>);
        final moved = DateTime.parse(day["date"] as String).add(shift);
        day["date"] = _dayKey(moved);
        day["isToday"] = day["date"] == today;
        return day;
      }).toList();
      return week;
    }).toList();

    return {
      "planId": raw["planId"],
      // Date only, the shape the API returns.
      "startedAt": _dayKey(generatedStart.add(shift)),
      "weeks": weeks,
    };
  }

  String _dayKey(DateTime d) =>
      "${d.year.toString().padLeft(4, '0')}-"
      "${d.month.toString().padLeft(2, '0')}-"
      "${d.day.toString().padLeft(2, '0')}";

  List<ChatMessage> messages() {
    return _chat ??= (_section("chat")["messages"] as List<dynamic>)
        .map((e) => ChatMessage.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Canned assistant turns. Deliberately generic and clearly demo-flavoured
  /// rather than pretending to be the real assistant's reasoning.
  List<ChatMessage> reply(String message) {
    final history = messages();
    final replies = [
      "Это демо-режим без подключения к серверу, поэтому отвечаю заготовкой. "
          "На боевом сервере здесь будет ответ ассистента по вашему отчёту.",
      "В демо-данных 225 продуктов в зелёной зоне, 32 в жёлтой и 28 в красной. "
          "Откройте «Результаты», чтобы посмотреть список и значения.",
      "Рецепты во вкладке «Рецепты» подобраны под этот же демо-отчёт: "
          "неподходящие помечены предупреждением по ингредиенту.",
    ];

    history.add(
      ChatMessage(
        id: "demo-u${history.length}",
        role: "user",
        messageType: "chat",
        content: message,
      ),
    );
    history.add(
      ChatMessage(
        id: "demo-a${history.length}",
        role: "assistant",
        messageType: "chat",
        content: replies[_replies++ % replies.length],
      ),
    );
    return List<ChatMessage>.from(history);
  }
}
